// Copyright 2020 The Tilt Brush Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_TiltBrush p_TiltBrush;
        
        private static SteamVR_Input_ActionSet_mixedreality p_mixedreality;
        
        public static SteamVR_Input_ActionSet_TiltBrush TiltBrush
        {
            get
            {
                return SteamVR_Actions.p_TiltBrush.GetCopy <SteamVR_Input_ActionSet_TiltBrush>();
            }
        }
        
        public static SteamVR_Input_ActionSet_mixedreality mixedreality
        {
            get
            {
                return SteamVR_Actions.p_mixedreality.GetCopy <SteamVR_Input_ActionSet_mixedreality>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_TiltBrush = ((SteamVR_Input_ActionSet_TiltBrush)(SteamVR_ActionSet.Create <SteamVR_Input_ActionSet_TiltBrush>("/actions/TiltBrush")));
            SteamVR_Actions.p_mixedreality = ((SteamVR_Input_ActionSet_mixedreality)(SteamVR_ActionSet.Create <SteamVR_Input_ActionSet_mixedreality>("/actions/mixedreality")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[]
            {
                    SteamVR_Actions.TiltBrush,
                    SteamVR_Actions.mixedreality};
        }
    }
}
