#!/bin/bash

#Runs post-process build scripts. 
#Must follow naming convention PostprocessBuildPlayer_* and be kept in the Assets/Editor folder.

echo "Running post-process build scripts."
for script in `/bin/ls -1 Assets/Editor | grep -i ^postprocessbuildplayer_ | grep -v [.]meta$`; do
    chmod +x "Assets/Editor/$script"
    echo "[[[ $script ]]]"
    "Assets/Editor/$script" "$@"
done